#
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python'
#- task: Bash@3
 # inputs:
  #  targetType: 'inline'
   # script: |
      #python3 -m pip install --upgrade pip
      #pip3 install -r requirements.txt
  #displayName: 'install dependencies'
- task: CmdLine@2
  inputs:
    script: 
      'mkdir data/output'
      #'touch test.txt'
  displayName: create directory

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/data/output/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true