#
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
  displayName: 'install dependencies'
- task: CmdLine@2
  inputs:
    script: 'mkdir data/output'
  displayName: create directory

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'YourSonarqubeServerEndpoint'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'heart_disease_build'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
